[project]
name = "da-vinci"
version = "3.0.0"
description = "Da Vinci is used to rapidly build AWS Cloud Native based systems"
authors = [{ name = "Jim Rosser" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.37.13",
    "requests>=2.32.3",
    "requests-auth-aws-sigv4==0.7",
]

[tool.hatch.build.targets.wheel]
packages = ["da_vinci"]

[tool.hatch.build.targets.wheel.force-include]
"da_vinci/Dockerfile" = "da_vinci/Dockerfile"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
